upstream forum-amak-site {
    server 127.0.0.1:9013;
    keepalive 8;
}

server {
    server_name forum.amak.site;
    access_log off;
#     access_log /opt/log/nginx/forum.amak.site.log;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;

        proxy_pass http://forum-amak-site/;
        proxy_redirect off;
    }

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/amak.site/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/amak.site/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

# sudo systemctl restart nginx


server {
    if ($host = forum.amak.site) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 0.0.0.0:80;
    server_name forum.amak.site;
    return 404; # managed by Certbot
}
